.TH MYSTRFUNCTIONS 3 "2025-09-20" "myutils" "Library functions"
.SH NAME
mystrlen \- return length of string
.br
mystrcpy \- copy string
.br
mystrncpy \- copy up to N characters
.br
mystrcat \- concatenate
.SH SYNOPSIS
int mystrlen(const char *s);
int mystrcpy(char *dest, const char *src);
int mystrncpy(char *dest, const char *src, int n);
int mystrcat(char *dest, const char *src);
.SH DESCRIPTION
These functions are custom implementations of basic string operations.
They are part of libmyutils used for this assignment.
.SH AUTHOR
Waqar Ali waqarali2020838@gmail.com
