.TH client 1 "2025-09-20" "client manual"
.SH NAME
client \- test program that uses libmyutils
.SH SYNOPSIS
client
.SH DESCRIPTION
This program demonstrates the functionality of mystrfunctions and myfilefunctions.
It is compiled and linked against libmyutils (static or dynamic).
.SH AUTHOR
Waqar Ali waqarali2020838@gmail.com
